[2024-03-24T22:18:27.155844+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Cannot assign null to property App\Application\v1\DTO\HistoricalQuotesRequest::$companySymbol of type string" at HistoricalQuotesRequest.php line 41 {"exception":"[object] (TypeError(code: 0): Cannot assign null to property App\\Application\\v1\\DTO\\HistoricalQuotesRequest::$companySymbol of type string at /var/www/src/Application/v1/DTO/HistoricalQuotesRequest.php:41)"} []
[2024-03-24T22:21:26.784329+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-03-24T22:21:28.855039+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-03-25T04:58:49.078266+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/\" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:181)"} []
[2024-03-25T05:26:18.207538+00:00] app.ERROR: An error occurred in HistoricalQuotesController: Too few arguments to function App\Application\v1\Service\CsvGeneratorService::generateCsv(), 2 passed in /var/www/src/Application/v1/Controller/HistoricalQuotesController.php on line 107 and exactly 3 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Application\\v1\\Service\\CsvGeneratorService::generateCsv(), 2 passed in /var/www/src/Application/v1/Controller/HistoricalQuotesController.php on line 107 and exactly 3 expected at /var/www/src/Application/v1/Service/CsvGeneratorService.php:16)"} []
[2024-03-25T05:26:45.566658+00:00] app.ERROR: An error occurred in HistoricalQuotesController: Too few arguments to function App\Application\v1\Service\CsvGeneratorService::generateCsv(), 2 passed in /var/www/src/Application/v1/Controller/HistoricalQuotesController.php on line 107 and exactly 3 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Application\\v1\\Service\\CsvGeneratorService::generateCsv(), 2 passed in /var/www/src/Application/v1/Controller/HistoricalQuotesController.php on line 107 and exactly 3 expected at /var/www/src/Application/v1/Service/CsvGeneratorService.php:16)"} []
[2024-03-25T05:46:12.581636+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T05:53:25.330764+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T05:55:29.732986+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T05:55:50.739345+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T05:58:28.955573+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:03:03.169547+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:04:28.491409+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:09:59.689049+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:09:59.689324+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2023-01-01     [email] => alexkorolkov1@gmail.com )  [] []
[2024-03-25T06:26:31.593115+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:26:44.860980+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:29:27.988681+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:30:12.856934+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:30:21.245464+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\CacheException: "Cannot find the "redis" extension nor the "predis/predis" package." at RedisTrait.php line 98 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\CacheException(code: 0): Cannot find the \"redis\" extension nor the \"predis/predis\" package. at /home/alex/projects/xm/app/vendor/symfony/cache/Traits/RedisTrait.php:98)"} []
[2024-03-25T06:32:46.086428+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:33:53.256126+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:33:54.500035+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2023-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2023-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:33:55.612983+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2023-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2023-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2023-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T06:35:31.287058+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:35:31.287298+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2023-01-01     [email] => alexkorolkov1@gmail.com )  [] []
[2024-03-25T06:37:00.503774+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:37:00.504797+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T06:37:01.581850+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:37:02.788276+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T06:38:21.800406+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:38:21.801601+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T06:38:22.785111+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:38:23.887046+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T06:40:11.349530+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:41:16.699542+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:42:03.512627+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:42:17.744837+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:42:17.745894+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T06:42:18.711764+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:42:19.729233+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T06:44:15.989228+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:44:15.990220+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T06:44:16.987506+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:44:18.090984+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T06:44:38.670471+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:55:13.978784+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:55:13.979271+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2023-01-01     [email] => alexkorolkov1@gmail.com )  [] []
[2024-03-25T06:59:03.924302+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T06:59:03.925455+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T06:59:05.001033+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T06:59:06.105560+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T07:02:05.911159+00:00] app.ERROR: TEST DATA:  [] []
[2024-03-25T07:02:05.912131+00:00] app.ERROR: TEST DATA: Array (     [companySymbol] => AAPL     [startDate] => 2022-01-01     [endDate] => 2022-01-31     [email] => example@example.com )  [] []
[2024-03-25T07:02:06.954948+00:00] app.ERROR: An error occurred in CsvGeneratorService: fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory {"exception":"[object] (PHPUnit\\Framework\\Error\\Warning(code: 2): fopen(../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv): Failed to open stream: No such file or directory at /home/alex/projects/xm/app/src/Application/v1/Service/CsvGeneratorService.php:19)"} []
[2024-03-25T07:02:08.068200+00:00] app.ERROR: An error occurred in MailService: Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unable to open path "../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv". {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage\" failed: Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:124)\n[previous exception] [object] (Symfony\\Component\\Mime\\Exception\\InvalidArgumentException(code: 0): Unable to open path \"../var/files/AAPL_from_2022-01-01_to_2022-01-31.csv\". at /home/alex/projects/xm/app/vendor/symfony/mime/Part/TextPart.php:150)"} []
[2024-03-25T07:25:52.220144+00:00] app.ERROR: TEST DATA:  [] []
